- name: Deploy Palo Alto Firewall
  hosts: localhost
  gather_facts: no
  tasks:
    - include: tasks/Create_folders.yaml

#    - include: tasks/Clone_Linux.yaml #IN THE FUTURE UTILIZE NESTED CHECKER
#    - include: tasks/Clone_Pan.yaml
#    - include: tasks/Configure_Management_Pan.yaml
#      loop: "{{ ubit }}"
#      loop_control:
#        index_var: idx
#    - include: tasks/Configure_Pan.yaml
#    - include: tasks/Power_On_Linux.yaml
#    - include: tasks/Assign_Permissions.yaml

